"use client";

import { useState, useEffect, useRef } from "react";
import { UserButton, useUser } from "@clerk/nextjs";
import { Clock, Play, Square, Receipt, Plus, Trash2, Download, DollarSign, Calendar, TrendingUp } from "lucide-react";

// Types
interface TimeEntry {
  id: string;
  description: string;
  startTime: Date;
  endTime?: Date;
  duration: number; // in seconds
  hourlyRate: number;
}

interface Invoice {
  id: string;
  clientName: string;
  email: string;
  entries: TimeEntry[];
  total: number;
  status: "draft" | "sent" | "paid";
  createdAt: Date;
}

// Generate PDF invoice
function generateInvoicePDF(invoice: Invoice) {
  // Dynamic import to avoid SSR issues
  import("jspdf").then(({ jsPDF }) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();

    // Header
    doc.setFontSize(24);
    doc.setTextColor(59, 130, 246);
    doc.text("INVOICE", pageWidth / 2, 25, { align: "center" });

    doc.setFontSize(12);
    doc.setTextColor(0);
    doc.text("FreelanceTimer", 20, 40);
    doc.setFontSize(10);
    doc.text("Professional Freelance Services", 20, 47);

    // Invoice details
    doc.setFontSize(10);
    doc.text(`Invoice #: INV-${Date.now().toString().slice(-6)}`, pageWidth - 70, 40);
    doc.text(`Date: ${new Date().toLocaleDateString()}`, pageWidth - 70, 47);
    doc.text(`Status: ${invoice.status.toUpperCase()}`, pageWidth - 70, 54);

    // Client info
    doc.setFontSize(12);
    doc.text("Bill To:", 20, 65);
    doc.setFontSize(11);
    doc.text(invoice.clientName, 20, 73);
    doc.setFontSize(10);
    doc.text(invoice.email, 20, 80);

    // Table header
    doc.setFillColor(59, 130, 246);
    doc.rect(20, 95, pageWidth - 40, 10, "F");
    doc.setTextColor(255);
    doc.setFontSize(10);
    doc.text("Description", 25, 101);
    doc.text("Hours", 120, 101);
    doc.text("Rate", 145, 101);
    doc.text("Amount", pageWidth - 35, 101, { align: "right" });

    // Table rows
    doc.setTextColor(0);
    let y = 115;
    invoice.entries.forEach((entry, i) => {
      if (i % 2 === 0) {
        doc.setFillColor(248, 250, 252);
        doc.rect(20, y - 5, pageWidth - 40, 10, "F");
      }
      doc.text(entry.description.substring(0, 40), 25, y);
      doc.text((entry.duration / 3600).toFixed(2), 120, y);
      doc.text(`$${entry.hourlyRate}/hr`, 145, y);
      doc.text(`$${((entry.duration / 3600) * entry.hourlyRate).toFixed(2)}`, pageWidth - 35, y, { align: "right" });
      y += 12;
    });

    // Total
    y += 5;
    doc.setDrawColor(200);
    doc.line(120, y, pageWidth - 20, y);
    y += 10;
    doc.setFontSize(12);
    doc.setTextColor(59, 130, 246);
    doc.text("TOTAL:", 120, y);
    doc.text(`$${invoice.total.toFixed(2)}`, pageWidth - 35, y, { align: "right" });

    // Footer
    doc.setFontSize(9);
    doc.setTextColor(128);
    doc.text("Thank you for your business!", pageWidth / 2, 270, { align: "center" });
    doc.text("Generated by FreelanceTimer", pageWidth / 2, 277, { align: "center" });

    doc.save(`invoice-${invoice.id}.pdf`);
  });
}

export default function Dashboard() {
  const { user } = useUser();
  const [isRunning, setIsRunning] = useState(false);
  const [currentEntry, setCurrentEntry] = useState<TimeEntry | null>(null);
  const [entries, setEntries] = useState<TimeEntry[]>([]);
  const [invoices, setInvoices] = useState<Invoice[]>([]);
  const [showNewEntry, setShowNewEntry] = useState(false);
  const [showInvoice, setShowInvoice] = useState(false);
  const [description, setDescription] = useState("");
  const [hourlyRate, setHourlyRate] = useState(50);
  const [elapsed, setElapsed] = useState(0);
  const [stats, setStats] = useState({ todayHours: 0, weekHours: 0, monthEarnings: 0 });
  const timerRef = useRef<NodeJS.Timeout | null>(null);

  // Load from localStorage
  useEffect(() => {
    const saved = localStorage.getItem("freelance-timer-entries");
    if (saved) {
      const parsed = JSON.parse(saved);
      setEntries(parsed.map((e: any) => ({
        ...e,
        startTime: new Date(e.startTime),
        endTime: e.endTime ? new Date(e.endTime) : undefined
      })));
    }
    const savedInvoices = localStorage.getItem("freelance-timer-invoices");
    if (savedInvoices) setInvoices(JSON.parse(savedInvoices));
  }, []);

  // Timer
  useEffect(() => {
    if (isRunning) {
      timerRef.current = setInterval(() => {
        setElapsed((e) => e + 1);
      }, 1000);
    } else {
      if (timerRef.current) clearInterval(timerRef.current);
    }
    return () => { if (timerRef.current) clearInterval(timerRef.current); };
  }, [isRunning]);

  // Stats
  useEffect(() => {
    const now = new Date();
    const todayStart = new Date(now.getFullYear(), now.getMonth(), now.getDate());
    const weekStart = new Date(todayStart);
    weekStart.setDate(weekStart.getDate() - weekStart.getDay());

    const todaySecs = entries
      .filter((e) => new Date(e.startTime) >= todayStart)
      .reduce((sum, e) => sum + e.duration, 0);
    const weekSecs = entries
      .filter((e) => new Date(e.startTime) >= weekStart)
      .reduce((sum, e) => sum + e.duration, 0);
    const monthEarnings = entries
      .filter((e) => new Date(e.startTime).getMonth() === now.getMonth())
      .reduce((sum, e) => sum + (e.duration / 3600) * e.hourlyRate, 0);

    setStats({
      todayHours: +(todaySecs / 3600).toFixed(1),
      weekHours: +(weekSecs / 3600).toFixed(1),
      monthEarnings: +monthEarnings.toFixed(2),
    });
  }, [entries]);

  const startTimer = () => {
    const entry: TimeEntry = {
      id: crypto.randomUUID(),
      description: description || "Untitled session",
      startTime: new Date(),
      duration: 0,
      hourlyRate,
    };
    setCurrentEntry(entry);
    setIsRunning(true);
    setElapsed(0);
    setShowNewEntry(false);
  };

  const stopTimer = () => {
    if (!currentEntry) return;
    const completed: TimeEntry = {
      ...currentEntry,
      endTime: new Date(),
      duration: elapsed,
    };
    const updated = [completed, ...entries];
    setEntries(updated);
    localStorage.setItem("freelance-timer-entries", JSON.stringify(updated));
    setIsRunning(false);
    setCurrentEntry(null);
    setElapsed(0);
    setDescription("");
  };

  const deleteEntry = (id: string) => {
    const updated = entries.filter((e) => e.id !== id);
    setEntries(updated);
    localStorage.setItem("freelance-timer-entries", JSON.stringify(updated));
  };

  const createInvoice = (entryIds: string[]) => {
    const selected = entries.filter((e) => entryIds.includes(e.id));
    const total = selected.reduce((sum, e) => sum + (e.duration / 3600) * e.hourlyRate, 0);
    const invoice: Invoice = {
      id: crypto.randomUUID(),
      clientName: "Client Name",
      email: "client@example.com",
      entries: selected,
      total,
      status: "draft",
      createdAt: new Date(),
    };
    const updated = [invoice, ...invoices];
    setInvoices(updated);
    localStorage.setItem("freelance-timer-invoices", JSON.stringify(updated));
    setShowInvoice(false);
    return invoice;
  };

  const formatTime = (secs: number) => {
    const h = Math.floor(secs / 3600);
    const m = Math.floor((secs % 3600) / 60);
    const s = secs % 60;
    return `${h.toString().padStart(2, "0")}:${m.toString().padStart(2, "0")}:${s.toString().padStart(2, "0")}`;
  };

  const formatDuration = (secs: number) => {
    const h = (secs / 3600).toFixed(1);
    return `${h}h`;
  };

  const [selectedEntries, setSelectedEntries] = useState<string[]>([]);
  const [showInvoiceBuilder, setShowInvoiceBuilder] = useState(false);
  const [clientName, setClientName] = useState("");
  const [clientEmail, setClientEmail] = useState("");

  const toggleSelect = (id: string) => {
    setSelectedEntries((prev) =>
      prev.includes(id) ? prev.filter((x) => x !== id) : [...prev, id]
    );
  };

  const buildAndDownloadInvoice = () => {
    if (selectedEntries.length === 0 || !clientName) return;
    const selected = entries.filter((e) => selectedEntries.includes(e.id));
    const total = selected.reduce((sum, e) => sum + (e.duration / 3600) * e.hourlyRate, 0);
    const invoice: Invoice = {
      id: crypto.randomUUID(),
      clientName,
      email: clientEmail,
      entries: selected,
      total,
      status: "draft",
      createdAt: new Date(),
    };
    generateInvoicePDF(invoice);
    setShowInvoiceBuilder(false);
    setSelectedEntries([]);
    setClientName("");
    setClientEmail("");
  };

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <header className="bg-white border-b border-gray-200 sticky top-0 z-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between items-center h-16">
            <div className="flex items-center gap-2">
              <div className="w-8 h-8 bg-blue-600 rounded-lg flex items-center justify-center">
                <Clock className="w-5 h-5 text-white" />
              </div>
              <span className="font-bold text-xl text-gray-900">FreelanceTimer</span>
            </div>
            <div className="flex items-center gap-4">
              <span className="text-sm text-gray-600 hidden sm:block">
                {user?.firstName || "Freelancer"}
              </span>
              <UserButton afterSignOutUrl="/" />
            </div>
          </div>
        </div>
      </header>

      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        {/* Stats */}
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-8">
          <div className="bg-white rounded-xl p-6 shadow-sm border border-gray-100">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 bg-blue-100 rounded-lg flex items-center justify-center">
                <Clock className="w-5 h-5 text-blue-600" />
              </div>
              <div>
                <p className="text-sm text-gray-500">Today</p>
                <p className="text-2xl font-bold text-gray-900">{stats.todayHours}h</p>
              </div>
            </div>
          </div>
          <div className="bg-white rounded-xl p-6 shadow-sm border border-gray-100">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 bg-green-100 rounded-lg flex items-center justify-center">
                <Calendar className="w-5 h-5 text-green-600" />
              </div>
              <div>
                <p className="text-sm text-gray-500">This Week</p>
                <p className="text-2xl font-bold text-gray-900">{stats.weekHours}h</p>
              </div>
            </div>
          </div>
          <div className="bg-white rounded-xl p-6 shadow-sm border border-gray-100">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 bg-indigo-100 rounded-lg flex items-center justify-center">
                <DollarSign className="w-5 h-5 text-indigo-600" />
              </div>
              <div>
                <p className="text-sm text-gray-500">This Month</p>
                <p className="text-2xl font-bold text-gray-900">${stats.monthEarnings}</p>
              </div>
            </div>
          </div>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          {/* Timer */}
          <div className="lg:col-span-1">
            <div className="bg-white rounded-2xl p-8 shadow-sm border border-gray-100 sticky top-24">
              <h2 className="text-lg font-semibold text-gray-900 mb-6">Time Tracker</h2>

              {/* Timer Display */}
              <div className="text-center mb-8">
                <div className="text-6xl font-mono font-bold text-gray-900 tracking-wider mb-2">
                  {formatTime(elapsed)}
                </div>
                {currentEntry && (
                  <p className="text-gray-500 text-sm">{currentEntry.description}</p>
                )}
              </div>

              {/* Description */}
              <div className="mb-4">
                <input
                  type="text"
                  placeholder="What are you working on?"
                  value={description}
                  onChange={(e) => setDescription(e.target.value)}
                  disabled={isRunning}
                  className="w-full px-4 py-3 border border-gray-200 rounded-xl focus:ring-2 focus:ring-blue-500 focus:border-transparent disabled:bg-gray-50 text-sm"
                />
              </div>

              {/* Hourly Rate */}
              <div className="mb-6">
                <label className="text-xs text-gray-500 mb-1 block">Hourly Rate ($)</label>
                <input
                  type="number"
                  value={hourlyRate}
                  onChange={(e) => setHourlyRate(Number(e.target.value))}
                  disabled={isRunning}
                  className="w-full px-4 py-3 border border-gray-200 rounded-xl focus:ring-2 focus:ring-blue-500 focus:border-transparent disabled:bg-gray-50 text-sm"
                />
              </div>

              {/* Timer Button */}
              {isRunning ? (
                <button
                  onClick={stopTimer}
                  className="w-full py-4 bg-red-500 hover:bg-red-600 text-white rounded-xl font-semibold flex items-center justify-center gap-2 transition-all shadow-lg hover:shadow-xl"
                >
                  <Square className="w-5 h-5" />
                  Stop Timer
                </button>
              ) : (
                <button
                  onClick={startTimer}
                  className="w-full py-4 bg-blue-600 hover:bg-blue-700 text-white rounded-xl font-semibold flex items-center justify-center gap-2 transition-all shadow-lg hover:shadow-xl"
                >
                  <Play className="w-5 h-5" />
                  Start Timer
                </button>
              )}

              {/* Quick entry button */}
              {!isRunning && (
                <p className="text-center text-xs text-gray-400 mt-3">
                  Or add a completed entry manually
                </p>
              )}
            </div>
          </div>

          {/* Entries & Invoices */}
          <div className="lg:col-span-2 space-y-6">
            {/* Time Entries */}
            <div className="bg-white rounded-2xl p-6 shadow-sm border border-gray-100">
              <div className="flex justify-between items-center mb-4">
                <h2 className="text-lg font-semibold text-gray-900">Time Entries</h2>
                {entries.length > 0 && (
                  <button
                    onClick={() => setShowInvoiceBuilder(true)}
                    className="text-sm px-4 py-2 bg-blue-50 text-blue-600 rounded-lg hover:bg-blue-100 font-medium flex items-center gap-1"
                  >
                    <Receipt className="w-4 h-4" />
                    Create Invoice
                  </button>
                )}
              </div>

              {entries.length === 0 ? (
                <div className="text-center py-12 text-gray-400">
                  <Clock className="w-12 h-12 mx-auto mb-3 opacity-30" />
                  <p>No time entries yet.</p>
                  <p className="text-sm">Start the timer to track your work!</p>
                </div>
              ) : (
                <div className="space-y-3">
                  {entries.map((entry) => (
                    <div
                      key={entry.id}
                      className="flex items-center gap-4 p-4 bg-gray-50 rounded-xl hover:bg-gray-100 transition"
                    >
                      <input
                        type="checkbox"
                        checked={selectedEntries.includes(entry.id)}
                        onChange={() => toggleSelect(entry.id)}
                        className="w-4 h-4 rounded border-gray-300 text-blue-600"
                      />
                      <div className="flex-1 min-w-0">
                        <p className="font-medium text-gray-900 truncate">{entry.description}</p>
                        <p className="text-xs text-gray-500">
                          {new Date(entry.startTime).toLocaleDateString()} at{" "}
                          {new Date(entry.startTime).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}
                        </p>
                      </div>
                      <div className="text-right">
                        <p className="font-semibold text-gray-900">{formatDuration(entry.duration)}</p>
                        <p className="text-xs text-gray-500">${((entry.duration / 3600) * entry.hourlyRate).toFixed(2)}</p>
                      </div>
                      <button
                        onClick={() => deleteEntry(entry.id)}
                        className="p-2 text-gray-400 hover:text-red-500 transition"
                      >
                        <Trash2 className="w-4 h-4" />
                      </button>
                    </div>
                  ))}
                </div>
              )}
            </div>

            {/* Invoices */}
            <div className="bg-white rounded-2xl p-6 shadow-sm border border-gray-100">
              <h2 className="text-lg font-semibold text-gray-900 mb-4">Invoices</h2>
              {invoices.length === 0 ? (
                <div className="text-center py-8 text-gray-400">
                  <Receipt className="w-10 h-10 mx-auto mb-3 opacity-30" />
                  <p className="text-sm">No invoices yet.</p>
                </div>
              ) : (
                <div className="space-y-3">
                  {invoices.map((inv) => (
                    <div
                      key={inv.id}
                      className="flex items-center justify-between p-4 bg-gray-50 rounded-xl"
                    >
                      <div>
                        <p className="font-medium text-gray-900">{inv.clientName}</p>
                        <p className="text-xs text-gray-500">
                          {inv.entries.length} entries ·{" "}
                          {new Date(inv.createdAt).toLocaleDateString()}
                        </p>
                      </div>
                      <div className="flex items-center gap-3">
                        <span
                          className={`text-xs px-2 py-1 rounded-full font-medium ${
                            inv.status === "paid"
                              ? "bg-green-100 text-green-700"
                              : inv.status === "sent"
                              ? "bg-blue-100 text-blue-700"
                              : "bg-gray-200 text-gray-600"
                          }`}
                        >
                          {inv.status}
                        </span>
                        <p className="font-bold text-gray-900">${inv.total.toFixed(2)}</p>
                        <button
                          onClick={() => generateInvoicePDF(inv)}
                          className="p-2 text-blue-600 hover:bg-blue-50 rounded-lg transition"
                        >
                          <Download className="w-4 h-4" />
                        </button>
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </div>
          </div>
        </div>
      </main>

      {/* Invoice Builder Modal */}
      {showInvoiceBuilder && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-2xl p-8 max-w-md w-full shadow-2xl">
            <h3 className="text-xl font-bold text-gray-900 mb-6">Create Invoice</h3>

            <div className="space-y-4 mb-6">
              <div>
                <label className="text-sm font-medium text-gray-700 mb-1 block">Client Name</label>
                <input
                  type="text"
                  value={clientName}
                  onChange={(e) => setClientName(e.target.value)}
                  placeholder="Acme Corp"
                  className="w-full px-4 py-3 border border-gray-200 rounded-xl focus:ring-2 focus:ring-blue-500"
                />
              </div>
              <div>
                <label className="text-sm font-medium text-gray-700 mb-1 block">Client Email</label>
                <input
                  type="email"
                  value={clientEmail}
                  onChange={(e) => setClientEmail(e.target.value)}
                  placeholder="billing@acme.com"
                  className="w-full px-4 py-3 border border-gray-200 rounded-xl focus:ring-2 focus:ring-blue-500"
                />
              </div>
              <div>
                <p className="text-sm text-gray-500 mb-2">
                  {selectedEntries.length} entries selected · Total: $
                  {entries
                    .filter((e) => selectedEntries.includes(e.id))
                    .reduce((sum, e) => sum + (e.duration / 3600) * e.hourlyRate, 0)
                    .toFixed(2)}
                </p>
              </div>
            </div>

            <div className="flex gap-3">
              <button
                onClick={() => {
                  setShowInvoiceBuilder(false);
                  setSelectedEntries([]);
                }}
                className="flex-1 py-3 border border-gray-200 rounded-xl font-medium text-gray-700 hover:bg-gray-50"
              >
                Cancel
              </button>
              <button
                onClick={buildAndDownloadInvoice}
                disabled={!clientName || selectedEntries.length === 0}
                className="flex-1 py-3 bg-blue-600 text-white rounded-xl font-medium hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
              >
                <Download className="w-4 h-4" />
                Download PDF
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
